name: Test branch
on: push

jobs:
  deploy-ssh-no-branch:
    name: Test deploying to a new branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Dummy Data
      run: |
        mkdir dummy
        echo "foobar" > "dummy/baz"
        echo "foobar" > "dummy/.bat"
    - name: Setup SSH Keys and known_hosts
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        SSH_PRIVATE_KEY: ${{ secrets.TESTING_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        cp action/resources/known_hosts_github.com ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${SSH_PRIVATE_KEY}"
    - name: Delete existing banch
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: git push git@github.com:s0/git-publish-subdir-action-tests.git +:refs/heads/branch-a
    - name: Deploy
      uses: ./
      env:
        REPO: git@github.com:s0/git-publish-subdir-action-tests.git
        BRANCH: branch-a
        FOLDER: dummy
        SSH_PRIVATE_KEY: ${{ secrets.TESTING_PRIVATE_KEY }}
  deploy-ssh-existing-branch:
    name: Test deploying to a pre-existing branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Dummy Data
      run: |
        mkdir dummy
        echo "foobar" > "dummy/baz"
        echo "foobar" > "dummy/.bat"
    - name: Deploy
      uses: ./
      env:
        REPO: git@github.com:s0/git-publish-subdir-action-tests.git
        BRANCH: branch-b
        FOLDER: dummy
        SSH_PRIVATE_KEY: ${{ secrets.TESTING_PRIVATE_KEY }}
  deploy-ssh-existing-branch-known_hosts:
    name: Test deploying to a pre-existing branch (with KNOWN_HOSTS_FILE)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Dummy Data
      run: |
        mkdir dummy
        echo "foobar" > "dummy/baz"
        echo "foobar" > "dummy/.bat"
    - name: Deploy
      uses: ./
      env:
        REPO: git@github.com:s0/git-publish-subdir-action-tests.git
        BRANCH: branch-c
        FOLDER: dummy
        SSH_PRIVATE_KEY: ${{ secrets.TESTING_PRIVATE_KEY }}
        KNOWN_HOSTS_FILE: action/resources/known_hosts_github.com
  deploy-ssh-twice:
    name: Test deploying multiple times in one job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Dummy Data
      run: |
        mkdir dummy1
        echo "foobar1" > "dummy1/baz"
        echo "foobar1" > "dummy1/.bat"
        mkdir dummy2
        echo "foobar2" > "dummy2/baz"
        echo "foobar2" > "dummy2/.bat"
    - name: Deploy
      uses: ./
      env:
        REPO: git@github.com:s0/git-publish-subdir-action-tests.git
        BRANCH: branch-d
        FOLDER: dummy1
        SSH_PRIVATE_KEY: ${{ secrets.TESTING_PRIVATE_KEY }}
    - name: Deploy
      uses: ./
      env:
        REPO: git@github.com:s0/git-publish-subdir-action-tests.git
        BRANCH: branch-d
        FOLDER: dummy2
        SSH_PRIVATE_KEY: ${{ secrets.TESTING_PRIVATE_KEY }}
  deploy-locally:
    name: Test deploying to another branch of same repo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Dummy Data
      run: |
        mkdir dummy
        echo "foobar" > "dummy/baz"
        echo "foobar" > "dummy/.bat"
    - name: Deploy
      uses: ./
      env:
        REPO: self
        BRANCH: test-branch
        FOLDER: dummy
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ci:
    name: Run Build and check output is checked-in
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: 'Build'
      run: |
        cd action
        npm install
        npm run build
    - name: Check no files have changes
      run: git diff --exit-code
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install NPM Packages
      run: |
        cd action
        npm install
    - name: Run Unit Tests
      run: |
        cd action
        npm run test
      env:
        GITHUB_SSH_PRIVATE_KEY: ${{ secrets.TESTING_PRIVATE_KEY }}
        GITHUB_SELF_TEST_REPO: ${{ github.repository }}
        GITHUB_SELF_TEST_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Submit to CodeCov
      uses: codecov/codecov-action@v1
      with:
        file: ./action/coverage.lcov
        fail_ci_if_error: true
